-- ==========================================
-- Gain EX — Complete Supabase / PostgreSQL Schema
-- Run this ENTIRE script in your Supabase SQL Editor
-- ==========================================

-- !! STEP 0 — REQUIRED: Create exec_sql helper function !!
CREATE OR REPLACE FUNCTION public.exec_sql(query_text TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result JSONB;
  upper_query TEXT;
BEGIN
  upper_query := ltrim(upper(query_text));
  IF upper_query LIKE 'SELECT%' OR upper_query LIKE 'WITH%' OR upper_query LIKE 'SHOW%' OR upper_query LIKE 'EXPLAIN%' THEN
    EXECUTE 'SELECT jsonb_agg(row_to_json(t)) FROM (' || query_text || ') t' INTO result;
    RETURN COALESCE(result, '[]'::JSONB);
  ELSIF (upper_query LIKE 'INSERT%' OR upper_query LIKE 'UPDATE%' OR upper_query LIKE 'DELETE%') AND upper_query LIKE '%RETURNING%' THEN
    EXECUTE 'WITH affected_rows AS (' || query_text || ') SELECT jsonb_agg(row_to_json(t)) FROM affected_rows t' INTO result;
    RETURN COALESCE(result, '[]'::JSONB);
  ELSE
    EXECUTE query_text;
    RETURN '[]'::JSONB;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.exec_sql(TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.exec_sql(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.exec_sql(TEXT) TO authenticated;

-- ==========================================
-- TABLE 1: USERS
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone_number VARCHAR(50),
  full_name VARCHAR(255),
  profile_pic TEXT,
  credit_score NUMERIC(5,2) DEFAULT 100.0,
  withdraw_enabled INTEGER DEFAULT 1 CHECK(withdraw_enabled IN (0, 1)),
  withdraw_limit NUMERIC(15,2) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'user' CHECK(role IN ('admin', 'employee', 'user')),
  balance NUMERIC(15,2) DEFAULT 0.0,
  demo_balance NUMERIC(15,2) DEFAULT 10000.0,
  status VARCHAR(50) DEFAULT 'active' CHECK(status IN ('active', 'frozen', 'blocked')),
  invite_code VARCHAR(100) UNIQUE,
  invited_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  real_account_active INTEGER DEFAULT 0 CHECK(real_account_active IN (0, 1)),
  kyc_status VARCHAR(50) DEFAULT 'unverified' CHECK(kyc_status IN ('unverified', 'pending', 'verified', 'rejected')),
  kyc_country VARCHAR(100),
  kyc_address TEXT,
  kyc_document_front TEXT,
  kyc_document_back TEXT,
  kyc_selfie TEXT,
  kyc_submitted_at VARCHAR(100),
  kyc_rejected_reason TEXT,
  currency VARCHAR(10) DEFAULT 'USD',
  is_test BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Safe migration: add is_test if missing
DO $m$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='users' AND column_name='is_test'
  ) THEN
    ALTER TABLE users ADD COLUMN is_test BOOLEAN DEFAULT FALSE;
  END IF;
END $m$;

-- Safe migration: add full_name if missing
DO $m$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='users' AND column_name='full_name'
  ) THEN
    ALTER TABLE users ADD COLUMN full_name VARCHAR(255);
  END IF;
END $m$;

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_invite_code ON users(invite_code);
CREATE INDEX IF NOT EXISTS idx_users_invited_by_id ON users(invited_by_id);

-- ==========================================
-- TABLE 2: PERMISSIONS (staff)
-- ==========================================
CREATE TABLE IF NOT EXISTS permissions (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  user_management INTEGER DEFAULT 0 CHECK(user_management IN (0, 1)),
  deposit_approval INTEGER DEFAULT 0 CHECK(deposit_approval IN (0, 1)),
  withdrawal_approval INTEGER DEFAULT 0 CHECK(withdrawal_approval IN (0, 1)),
  trade_monitoring INTEGER DEFAULT 0 CHECK(trade_monitoring IN (0, 1)),
  live_support INTEGER DEFAULT 0 CHECK(live_support IN (0, 1)),
  full_access INTEGER DEFAULT 0 CHECK(full_access IN (0, 1)),
  see_all_users INTEGER DEFAULT 0 CHECK(see_all_users IN (0, 1))
);

-- ==========================================
-- TABLE 3: INVITE CODES
-- ==========================================
CREATE TABLE IF NOT EXISTS invite_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) UNIQUE NOT NULL,
  created_by_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  used_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- TABLE 4: DEPOSITS
-- ==========================================
CREATE TABLE IF NOT EXISTS deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  method VARCHAR(50) NOT NULL CHECK(method IN ('USDT', 'USDC', 'BANK')),
  amount NUMERIC(15,2) NOT NULL,
  details TEXT,
  proof_text TEXT,
  proof_file TEXT,
  status VARCHAR(50) DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ,
  resolved_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- ==========================================
-- TABLE 5: WITHDRAWALS
-- ==========================================
CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  method VARCHAR(50) NOT NULL CHECK(method IN ('USDT', 'USDC', 'BANK')),
  amount NUMERIC(15,2) NOT NULL,
  payout_details TEXT NOT NULL,
  actual_payout NUMERIC(15,2),
  status VARCHAR(50) DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ,
  resolved_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- ==========================================
-- TABLE 6: TRADE OPTIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS trade_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  duration INTEGER UNIQUE NOT NULL,
  commission_pct NUMERIC(5,2) NOT NULL
);

-- ==========================================
-- TABLE 7: TRADES
-- ==========================================
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  coin VARCHAR(50) NOT NULL,
  direction VARCHAR(10) NOT NULL CHECK(direction IN ('UP', 'DOWN')),
  amount NUMERIC(15,2) NOT NULL,
  duration INTEGER NOT NULL,
  commission_pct NUMERIC(5,2) NOT NULL,
  open_price NUMERIC(20,8) NOT NULL,
  close_price NUMERIC(20,8),
  status VARCHAR(50) DEFAULT 'active' CHECK(status IN ('active', 'win', 'lose', 'refunded')),
  admin_control VARCHAR(10) DEFAULT 'none' CHECK(admin_control IN ('none', 'win', 'lose')),
  is_demo INTEGER DEFAULT 0 CHECK(is_demo IN (0, 1)),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL,
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_trades_user_id ON trades(user_id);
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);

-- ==========================================
-- TABLE 8: LEDGER
-- ==========================================
CREATE TABLE IF NOT EXISTS ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL CHECK(type IN (
    'deposit','withdrawal','trade_win','trade_lose',
    'admin_add','admin_subtract','referral_commission'
  )),
  amount NUMERIC(15,2) NOT NULL,
  description TEXT,
  balance_after NUMERIC(15,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- TABLE 9: SETTINGS
-- ==========================================
CREATE TABLE IF NOT EXISTS settings (
  key VARCHAR(255) PRIMARY KEY,
  value TEXT NOT NULL
);

-- ==========================================
-- TABLE 10: EMAIL VERIFICATIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS email_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL CHECK(type IN ('current_email', 'new_email')),
  email VARCHAR(255) NOT NULL,
  code VARCHAR(10) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  verified INTEGER DEFAULT 0 CHECK(verified IN (0, 1)),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- TABLE 11: PROFILE POSTS  (NEW — was missing)
-- ==========================================
CREATE TABLE IF NOT EXISTS profile_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  media_url TEXT NOT NULL,
  media_type VARCHAR(50) NOT NULL CHECK(media_type IN ('image', 'gif', 'video')),
  description TEXT DEFAULT '',
  likes_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_profile_posts_user_id ON profile_posts(user_id);

-- ==========================================
-- TABLE 12: PROFILE POST LIKES  (NEW — was missing)
-- ==========================================
CREATE TABLE IF NOT EXISTS profile_post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES profile_posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post_id ON profile_post_likes(post_id);

-- ==========================================
-- TABLE 13: PROFILE COMMENTS  (NEW — was missing)
-- ==========================================
CREATE TABLE IF NOT EXISTS profile_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES profile_posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_profile_comments_post_id ON profile_comments(post_id);

-- ==========================================
-- TABLE 14: FRIENDS  (NEW — was missing)
-- ==========================================
CREATE TABLE IF NOT EXISTS friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id1 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user_id2 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(50) DEFAULT 'pending' CHECK(status IN ('pending', 'accepted')),
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id1, user_id2)
);

CREATE INDEX IF NOT EXISTS idx_friends_user_id1 ON friends(user_id1);
CREATE INDEX IF NOT EXISTS idx_friends_user_id2 ON friends(user_id2);

-- ==========================================
-- SEED DATA
-- ==========================================

-- Default Trading Options
INSERT INTO trade_options (duration, commission_pct) VALUES
  (20, 5.0), (60, 4.0), (120, 3.0), (300, 2.0)
ON CONFLICT (duration) DO NOTHING;

-- Default System Settings
INSERT INTO settings (key, value) VALUES
  ('usdt_deposit_address', '0x1234567890abcdef1234567890abcdef12345678'),
  ('usdc_deposit_address', '0xabcdef1234567890abcdef1234567890abcdef12'),
  ('bank_deposit_details', 'Bank: Gain EX Global Bank\nAccount Number: 9876543210\nAccount Name: Gain EX INC\nIFSC/BIC Code: GAINEX999'),
  ('deposit_usdt_enabled', 'true'),
  ('deposit_usdc_enabled', 'true'),
  ('deposit_bank_enabled', 'true'),
  ('withdrawal_usdt_enabled', 'true'),
  ('withdrawal_usdc_enabled', 'true'),
  ('withdrawal_bank_enabled', 'true'),
  ('crypto_visible_coins', '["BTC","ETH","SOL","BNB","DOGE","XRP","ADA","AVAX","MATIC","LINK","LTC","DOT","TRX","UNI","ATOM"]'),
  ('forex_visible_pairs', '["EUR/USD","USD/CAD","GBP/USD","USD/JPY","AUD/USD"]'),
  ('combine_trades_control', 'false'),
  ('combine_trades_outcome', 'none'),
  ('currency_rate_INR', '83.5'),
  ('currency_rate_PKR', '278.0'),
  ('currency_rate_BDT', '117.0'),
  ('currency_rate_NPR', '133.0'),
  ('currency_rate_USD', '1.0'),
  ('referral_commission_pct', '5.0')
ON CONFLICT (key) DO NOTHING;

-- Default Admin Account (Password: admin123)
INSERT INTO users (username, password_hash, role, invite_code)
VALUES (
  'admin',
  '$2a$10$89Jd7UesB5X4L9/414iUveU5H/rVsz6f2Z.aVzN6.n5fU3u3Yx35O',
  'admin',
  'ADMIN777'
) ON CONFLICT (username) DO NOTHING;

-- Admin full permissions
INSERT INTO permissions (user_id, user_management, deposit_approval, withdrawal_approval, trade_monitoring, full_access, see_all_users)
SELECT id, 1, 1, 1, 1, 1, 1 FROM users WHERE username = 'admin'
ON CONFLICT (user_id) DO NOTHING;

-- Admin invite code
INSERT INTO invite_codes (code, created_by_id)
SELECT 'ADMIN777', id FROM users WHERE username = 'admin'
ON CONFLICT (code) DO NOTHING;
